image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - rm -rf .terraform
  - terraform --version
  - if [[ $ENVIRONMENT == "dev" ]] then export GOOGLE_APPLICATION_CREDENTIALS=${GCP_SERVICE_KEY_DEV_FILE} ; fi
  - if [[ $ENVIRONMENT == "test" ]] then export GOOGLE_APPLICATION_CREDENTIALS=${GCP_SERVICE_KEY_TEST_FILE} ; fi
  - if [[ $ENVIRONMENT == "prod" ]] then export GOOGLE_APPLICATION_CREDENTIALS=${GCP_SERVICE_KEY_PROD_FILE} ; fi
  - 'sed -i s"/ENVIRONMENT/$ENVIRONMENT/"g backend.tf'
  - terraform init

stages:
  - validate
  - plan
  - apply
  - destroy

############### validate #################
.validate:
  stage: validate
  script:
    - terraform validate

validate-dev:
  extends:
    - .validate
  variables:
    ENVIRONMENT: dev
  except:
    - master
    - /^release.*$/
    - /^hotfix.*$/
    - tags

validate-test:
  extends:
    - .validate
  variables:
    GCP_SERVICE_ACCOUNT_KEY: $GCP_SERVICE_ACCOUNT_KEY_TEST
    ENVIRONMENT: test
  only:
    - /^release.*$/
    - /^hotfix.*$/

validate-prod:
  extends:
    - .validate
  variables:
    GCP_SERVICE_ACCOUNT_KEY: $GCP_SERVICE_ACCOUNT_KEY_PROD
    ENVIRONMENT: prod
  only:
    - tags
  except:
    - branches

############### plan #################

.plan:
  stage: plan
  script:
    - terraform plan -var-file=${ENV_FILE}

plan-dev:
  extends:
    - .plan
  variables:
    GCP_SERVICE_ACCOUNT_KEY: $GCP_SERVICE_ACCOUNT_KEY_DEV
    ENVIRONMENT: dev
    ENV_FILE: dev.tfvars
  except:
    - master
    - /^release.*$/
    - /^hotfix.*$/
    - tags

plan-test:
  extends:
    - .plan
  variables:
    GCP_SERVICE_ACCOUNT_KEY: $GCP_SERVICE_ACCOUNT_KEY_TEST
    ENVIRONMENT: test
    ENV_FILE: test.tfvars
  only:
    - /^release.*$/
    - /^hotfix.*$/

plan-prod:
  extends:
    - .plan
  variables:
    GCP_SERVICE_ACCOUNT_KEY: $GCP_SERVICE_ACCOUNT_KEY_PROD
    ENVIRONMENT: prod
    ENV_FILE: prod.tfvars
  only:
    - tags
  except:
    - branches

############### apply #################

.apply:
  stage: apply
  script:
    - terraform apply -auto-approve -var-file=${ENV_FILE}
  when: manual

apply-dev:
  extends:
    - .apply
  variables:
    GCP_SERVICE_ACCOUNT_KEY: $GCP_SERVICE_ACCOUNT_KEY_DEV
    ENVIRONMENT: dev
    ENV_FILE: dev.tfvars
  except:
    - master
    - /^release.*$/
    - /^hotfix.*$/
    - tags

apply-test:
  extends:
    - .apply
  variables:
    GCP_SERVICE_ACCOUNT_KEY: $GCP_SERVICE_ACCOUNT_KEY_TEST
    ENVIRONMENT: test
    ENV_FILE: test.tfvars
  only:
    - /^release.*$/
    - /^hotfix.*$/

apply-prod:
  extends:
    - .apply
  variables:
    GCP_SERVICE_ACCOUNT_KEY: $GCP_SERVICE_ACCOUNT_KEY_PROD
    ENVIRONMENT: prod
    ENV_FILE: prod.tfvars
  only:
    - tags
  except:
    - branches

############### clean up #################

.destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve -var-file=${ENV_FILE}
  when: manual

destroy-dev:
  extends:
    - .destroy
  variables:
    GCP_SERVICE_ACCOUNT_KEY: $GCP_SERVICE_ACCOUNT_KEY_DEV
    ENVIRONMENT: dev
    ENV_FILE: dev.tfvars
  except:
    - master
    - /^release.*$/
    - /^hotfix.*$/
    - tags

destroy-test:
  extends:
    - .destroy
  variables:
    GCP_SERVICE_ACCOUNT_KEY: $GCP_SERVICE_ACCOUNT_KEY_TEST
    ENVIRONMENT: test
    ENV_FILE: test.tfvars
  only:
    - /^release.*$/
    - /^hotfix.*$/

destroy-prod:
  extends:
    - .destroy
  variables:
    GCP_SERVICE_ACCOUNT_KEY: $GCP_SERVICE_ACCOUNT_KEY_PROD
    ENVIRONMENT: prod
    ENV_FILE: prod.tfvars
  only:
    - tags
  except:
    - branches